In [14]:
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
from datetime import datetime

In [15]:
remaining=pd.read_csv('second-round-seat-matrix.csv')
college = pd.read_csv('final_college_list.csv')
college['College Code'] = college['College Code'].str[:6]

In [16]:
remaining = remaining.sort_values(by='College Code')
merged_df = remaining.merge(college, on='College Code', how='left')

current_date = datetime.now().strftime("%B %Y")

In [17]:
merged_df

,College Code,1G,1H,2AG,2AH,2BG,2BH,3AG,3AH,3BG,...,GMH,NKN,PH,SCG,SCH,STG,STH,XD,Total,College Name
0,C401MC,0,0,3,0,0,0,0,0,0,...,0,0,1,3,0,1,0,0,8,ACHARYA INSTITUTE OF MANAGEMENT AND SCIENCES P...
1,C402MC,0,0,0,0,0,0,0,0,0,...,1,0,3,5,0,0,1,0,10,ACHARYA INSTITUTE OF GRADUATE STUDIES DR SARVE...
2,C403MC,0,0,3,1,0,0,0,0,2,...,3,0,3,3,1,3,0,0,19,ADMINISTRATIVE MANAGEMENT COLLEGE
3,C407MC,0,0,0,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,2,ANGADI INSTITUTE OF TECHNOLOGY AND MANAGEMENT ...
4,C408MC,0,0,0,0,0,0,0,0,0,...,1,0,1,3,0,1,0,0,6,B V V SANGHA'S BASAVESHWAR ENGINEERING COLLEGE...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,C575MC,0,0,9,0,0,0,0,0,3,...,3,0,5,14,2,3,1,0,41,PRESIDENCY UNIVESITY ITTAGALPURA RAJANAKUNTE Y...
110,C576MC,0,0,4,0,0,0,0,0,2,...,1,0,2,6,1,2,1,0,19,RV INSTITUTE OF TECHNOLOGY AND MANAGEMENT KOTH...
111,C578MC,0,0,1,0,0,0,0,0,1,...,1,0,2,1,0,0,0,0,6,SESHADRIPURAM COLLEGE TUMAKURU VIKASABHARATI C...
112,C579MC,0,0,3,0,0,1,0,0,1,...,0,0,2,3,0,2,0,0,12,ST PHILOMENA'S COLLEGE BANNIMANTAP MYSORE
113,C580MC,0,0,0,5,0,2,0,1,0,...,12,0,3,0,6,0,3,0,34,VTU POST GRADUATE CENTER AND SKILL DEVELOPMENT...

In [18]:
def save_seat_matixx_from_remaining_df(df,headline, filename='seat_matrix.pdf'):
    with PdfPages(filename) as pdf:
        college_count = 0
        page_number = 1
        fig, ax = plt.subplots(figsize=(20, 14))
        ax.axis('off')

        title_y_position = 0.98

        # Main title
        ax.text(0.5, title_y_position, headline, 
                fontsize=20, ha='center', va='top', fontfamily='DejaVu Sans Mono')
        # Current date
        ax.text(0.95, title_y_position, current_date, fontsize=12,  
                ha='right', va='top', fontfamily='DejaVu Sans Mono')

        # Iterate through each college group
        for (college_code, college_name), group in df.groupby(['College Code', 'College Name']):
            if college_count % 10 == 0 and college_count != 0:
                # Add page number to each page
                ax.text(0.95, 0.01, f'Page {page_number}', fontsize=12, ha='right', va='bottom', fontfamily='DejaVu Sans Mono')
                pdf.savefig(fig, bbox_inches='tight', pad_inches=0.2)
                plt.close(fig)
                page_number += 1
                fig, ax = plt.subplots(figsize=(20, 14))
                ax.axis('off')
                ax.text(0.5, title_y_position, headline, 
                        fontsize=20, ha='center', va='top', fontfamily='DejaVu Sans Mono')
                ax.text(0.95, title_y_position, current_date, fontsize=12, ha='right', va='top', fontfamily='DejaVu Sans Mono')

            # College title
            college_title_y = title_y_position - 0.05 - (college_count % 10) * 0.09
            ax.text(0.05, college_title_y, f"{college_code} - {college_name}", 
                    fontsize=14, ha='left', va='top', fontfamily='DejaVu Sans Mono')

            # Display cutoff data for each college
            cutoff_data = group.iloc[:, 1:-1]
            table_start_y = college_title_y - 0.075
            table = ax.table(cellText=cutoff_data.values, colLabels=cutoff_data.columns, 
                             cellLoc='center', loc='center', bbox=[0.05, table_start_y, 0.8, 0.05])
            table.auto_set_font_size(False)
            table.set_fontsize(10)
            table.scale(1.2, 0.5)

            # Style the table
            for (i, j), cell in table.get_celld().items():
                if i == 0:
                    cell.set_text_props(color='black', fontsize=10, fontfamily='DejaVu Sans Mono')
                    cell.set_facecolor('#f4f4f4')
                else:
                    cell.set_text_props(fontfamily='DejaVu Sans Mono')
                    cell.set_facecolor('#FFFFFF')
                    if cutoff_data.iloc[i - 1, j] == '--':
                        cell.set_facecolor('#F9F9F9')
            
            college_count += 1

        # Save the final page and add the page number
        ax.text(0.95, 0.01, f'Page {page_number}', fontsize=12, ha='right', va='bottom', fontfamily='DejaVu Sans Mono')
        pdf.savefig(fig, bbox_inches='tight', pad_inches=0.15)
        plt.close(fig)

In [19]:
save_seat_matixx_from_remaining_df(merged_df,"Second Round - Seat Matrix PGCET MCA 2023")




print("successsssssssssss")

successsssssssssss